import React from 'react';
import { AlertTriangle, ArrowRight, CheckCircle2, Info, Save, Scale, ShieldAlert } from 'lucide-react';
import { Button, EvidenceBadge, ScoreMeter, SourceMeta } from './UiPrimitives';
import { formatCurrencyUsd, formatPercent } from '../../utils/formatters';

const ResultDossier = ({ result, onRevise, onSave, onCompare }) => {
  if (!result) return null;
  const drivers = result.featureContributions || [];
  const contributionMax = Math.max(...drivers.map((driver) => Number(driver.weight) || 0), 1);
  return <section className="sp-decision-strip" aria-labelledby="result-dossier-heading">
    <div className="sp-decision-cell"><div className="flex flex-wrap items-center gap-2"><span className="sp-decision-label" id="result-dossier-heading">Review result</span><EvidenceBadge state={result.source === 'saved_record' ? 'reference' : 'source'}>{result.source === 'saved_record' ? 'Reference record' : 'Model response'}</EvidenceBadge></div><div className="mt-3"><ScoreMeter dark value={result.successProbability} caption={result.statusTier} /></div><div className="mt-4 grid grid-cols-2 gap-2"><div><div className="sp-decision-label">Confidence</div><div className="mt-1 font-mono text-sm">{formatPercent(result.confidenceScore)}</div></div><div><div className="sp-decision-label">Model version</div><div className="mt-1 text-xs">{result.model_version || result.modelVersion || 'Not returned'}</div></div></div><p className="sp-decision-copy mt-4"><Info size={13} className="mr-1 inline" />{result.source === 'saved_record' ? 'This saved record does not include current source or driver metadata.' : `Capital evaluated: ${formatCurrencyUsd(result.fundingTotalUsd)} across ${result.fundingRounds ?? '—'} round(s).`}</p></div>
    <div className="sp-decision-cell"><div className="sp-decision-label">Top drivers</div>{drivers.length ? <div className="sp-decision-grid">{drivers.slice(0, 4).map((driver, index) => <div className={`sp-driver-row ${driver.impact === 'Positive' ? 'is-positive' : driver.impact === 'Review' ? 'is-warning' : ''}`} key={`${driver.name}-${index}`}><span className="truncate">{driver.name}</span><div className="sp-driver-bar"><span style={{ width: `${Math.min(100, ((Number(driver.weight) || 0) / contributionMax) * 100)}%` }} /></div><span className="sp-driver-impact">{driver.impact || '—'}</span></div>)}</div> : <p className="sp-decision-copy mt-3">Driver details unavailable for this saved record.</p>}</div>
    <div className="sp-decision-cell"><div className="sp-decision-label">Needs review</div><div className="mt-3 grid gap-3">{(result.riskFactors?.length ? result.riskFactors.slice(0, 3) : ['Confirm returned source and model details before sharing']).map((risk, index) => <div className="flex items-start gap-2" key={index}><AlertTriangle size={14} className="mt-0.5 shrink-0 text-[#d8a841]" /><div><strong className="block text-xs">{risk}</strong><span className="sp-decision-copy">Review against your current records.</span></div></div>)}{result.strengths?.slice(0, 1).map((strength, index) => <div className="flex items-start gap-2" key={`strength-${index}`}><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-[#9ee5d7]" /><div><strong className="block text-xs">{strength}</strong><span className="sp-decision-copy">Returned strength, not a guarantee.</span></div></div>)}</div></div>
    <div className="sp-decision-cell"><div className="sp-decision-label">Decision actions</div><p className="sp-decision-copy mt-3">Use the model result as a review input, not an eligibility or investment decision.</p><div className="sp-decision-actions mt-4"><Button variant="primary" onClick={onSave}><Save size={14} />Save evaluation</Button><Button onClick={onRevise}><ArrowRight size={14} />Revise inputs</Button><Button onClick={onCompare}><Scale size={14} />Compare benchmarks</Button></div></div>
  </section>;
};

export default ResultDossier;
