import React from 'react';
import { BookOpen, ExternalLink, FileCode2, LifeBuoy } from 'lucide-react';
import { Button, EvidenceBadge, PageHeader } from '../components/workspace/UiPrimitives';

const topics = [
  ['Run an estimate', 'Start with the facts you have, review missing fields, then run the model. A result is an estimate—not a funding, grant, or investment decision.'],
  ['Read a result', 'Use the score, confidence, returned drivers, risks, and recommendations together. If a field was not returned, StartupPulse shows an em dash or an unavailable state.'],
  ['Review saved evaluations', 'Portfolio contains returned history from the API. Reference records can lack source dates or feature contributions; those gaps remain visible.'],
  ['Research funding', 'Funding Research compares returned records and exposes source links when the backend provides them. Source status is shown per row.'],
  ['Draft student material', 'Student Workspace drafts are editable working documents. Confirm current SSIP, institution, and government requirements before applying.'],
];

const HelpDocsPage = ({ mode = 'help', onNavigate }) => <div className="sp-page"><PageHeader eyebrow={mode === 'docs' ? 'Utility / API docs' : 'Utility / Help'} title={mode === 'docs' ? 'API docs' : 'Help & docs'} description={mode === 'docs' ? 'Reference the API surfaces available in this deployment.' : 'Task-first guidance for using StartupPulse responsibly.'} status={<><span>{mode === 'docs' ? 'Endpoint names below mirror the connected FastAPI service.' : 'Need a destination? Every help item links back to a real workspace area.'}</span><EvidenceBadge state="source">Documentation surface</EvidenceBadge></>} />{mode === 'help' ? <div className="sp-utility-grid">{topics.map(([title, description]) => <article className="sp-utility-card" key={title}><div className="flex items-center gap-2"><LifeBuoy size={16} className="text-sp-cobalt" /><h3>{title}</h3></div><p>{description}</p></article>)}</div> : <div className="sp-grid-two"><section className="sp-panel"><div className="sp-panel-header"><div className="sp-panel-heading"><span className="sp-eyebrow">Connected endpoints</span><h2 className="sp-panel-title">FastAPI surface</h2></div><FileCode2 size={17} className="text-sp-cobalt" /></div><div className="sp-panel-body"><div className="grid gap-3">{['GET /health', 'POST /api/auth/login', 'POST /api/auth/register', 'GET /api/presets', 'POST /api/predict', 'GET /api/predictions/history', 'GET /api/analytics/model-metrics', 'GET /api/funding/deals', 'GET /api/gujarat-ecosystem/schemes'].map((endpoint) => <code key={endpoint} className="block rounded-sp-control border border-sp-rule bg-sp-canvas-soft px-3 py-2 text-xs text-sp-ink">{endpoint}</code>)}</div></div></section><section className="sp-panel"><div className="sp-panel-header"><div className="sp-panel-heading"><span className="sp-eyebrow">Request policy</span><h2 className="sp-panel-title">What is not exposed</h2></div><BookOpen size={17} className="text-sp-cobalt" /></div><div className="sp-panel-body grid gap-4"><p className="text-sm text-sp-muted">Password reset, billing, file export, and source freshness metadata are not currently exposed by the backend. The UI shows explicit unavailable states instead of claiming success.</p><Button variant="secondary" onClick={() => onNavigate('help')}><ExternalLink size={14} />Read usage guidance</Button></div></section></div>}</div>;

export default HelpDocsPage;
