import React, { useMemo, useState } from 'react';
import { Search as SearchIcon } from 'lucide-react';
import { fundingAPI, gujaratAPI, predictionAPI } from '../api';
import { useAsyncResource } from '../hooks/useAsyncResource';
import { normalizeDistrictDirectory, normalizeFundingDeal, normalizeGujaratSchemes, normalizeHistoryItem } from '../utils/normalizers';
import { Button, EmptyState, ErrorState, EvidenceBadge, PageHeader, SkeletonRows } from '../components/workspace/UiPrimitives';
import { ROUTES } from '../utils/routes';

const SearchPage = ({ onNavigate }) => {
  const [query, setQuery] = useState('');
  const resource = useAsyncResource(async () => { const [history, presets, deals, schemes, directory] = await Promise.all([predictionAPI.getHistory(), predictionAPI.getPresets(), fundingAPI.getDeals({}), gujaratAPI.getSchemes(), gujaratAPI.getDistrictsAndHubs()]); return { history: history.data || [], presets: presets.data || [], deals: deals.data || [], schemes: schemes.data, directory: directory.data }; }, [], { normalize: (value) => ({ evaluations: value.history.map(normalizeHistoryItem), benchmarks: value.presets, funding: value.deals.map(normalizeFundingDeal), schemes: normalizeGujaratSchemes(value.schemes), labs: Object.values(normalizeDistrictDirectory(value.directory).directory || {}).flatMap((district) => district.incubators || []) }) });
  const results = useMemo(() => { const normalized = query.trim().toLowerCase(); if (!normalized || !resource.data) return []; const match = (value) => String(value || '').toLowerCase().includes(normalized); return [...resource.data.evaluations.map((item) => ({ type: 'Evaluation', title: item.startupName, description: `${item.primaryCategory} · ${item.countryCode}`, route: ROUTES.portfolio, state: 'Saved evaluation' })), ...resource.data.benchmarks.filter((item) => match(item.name) || match(item.primary_category)).map((item) => ({ type: 'Benchmark', title: item.name?.split(' – ')[0] || item.name, description: `${item.primary_category || '—'} · Reference record`, route: ROUTES.evaluate, state: 'Reference record' })), ...resource.data.funding.filter((item) => match(item.startup_name) || match(item.sector) || match(item.lead_investors)).map((item) => ({ type: 'Funding record', title: item.startupName, description: `${item.amount} · ${item.round}`, route: ROUTES.funding, state: item.sourceUrl ? 'Source available' : 'Source unavailable' })), ...resource.data.schemes.filter((item) => match(item.name) || match(item.description)).map((item) => ({ type: 'Scheme', title: item.name, description: item.fund_pool || 'Scheme reference', route: ROUTES.student, state: 'Source available' })), ...resource.data.labs.filter((item) => match(item.name) || match(item.focus)).map((item) => ({ type: 'Lab', title: item.name, description: item.focus || 'Gujarat directory record', route: ROUTES.student, state: 'Directory record' }))]; }, [query, resource.data]);
  return <div className="sp-page"><PageHeader eyebrow="Utility / Search" title="Search StartupPulse" description="Search returned evaluations, benchmark records, funding research, schemes, and Gujarat labs from one place." status={<><span>{resource.status === 'error' ? 'Some datasets could not be loaded.' : 'Search uses data returned by the current endpoints.'}</span>{query && <span>{results.length} result{results.length === 1 ? '' : 's'}</span>}</>} /><div className="sp-panel p-4"><div className="sp-search-field"><SearchIcon size={16} aria-hidden="true" /><input autoFocus className="sp-control" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a venture, sector, scheme, lab, or investor" aria-label="Search StartupPulse" /></div></div>{resource.status === 'loading' && <div className="sp-panel p-4"><SkeletonRows count={6} /></div>}{resource.status === 'error' && <ErrorState title="Search data unavailable" description="Search could not load all supported record types. Retry to refresh the index." onRetry={resource.retry} />}{resource.status === 'ready' && !query && <div className="sp-panel"><EmptyState title="Start with a venture or sector" description="Try Zerodha, Gujarat, funding, SSIP, or a lab name." /></div>}{resource.status === 'ready' && query && results.length === 0 && <div className="sp-panel"><EmptyState title={`No results for “${query}”`} description="Try a broader venture name, sector, scheme, or investor." action={<Button variant="secondary" onClick={() => setQuery('')}>Clear search</Button>} /></div>}{results.length > 0 && <div className="sp-panel"><div className="sp-panel-header"><div className="sp-panel-heading"><span className="sp-eyebrow">Search results</span><h2 className="sp-panel-title">Matched records</h2></div><EvidenceBadge>Returned data</EvidenceBadge></div><div className="grid divide-y divide-sp-rule">{results.map((result, index) => <button type="button" className="flex items-start justify-between gap-4 p-4 text-left hover:bg-sp-canvas-soft sp-focus" key={`${result.type}-${result.title}-${index}`} onClick={() => onNavigate(result.route)}><span className="min-w-0"><span className="flex flex-wrap items-center gap-2"><strong className="text-sm">{result.title}</strong><EvidenceBadge>{result.type}</EvidenceBadge></span><span className="mt-1 block text-xs text-sp-muted">{result.description}</span></span><span className="shrink-0 text-[10px] font-bold text-sp-cobalt">{result.state} →</span></button>)}</div></div>}</div>;
};

export default SearchPage;
